[project]
name = 'DreamChain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dream-analysis]
path = 'contracts/dream-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.dream-nft]
path = 'contracts/dream-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
